### ISSUE TITLE
make go-base fails

### ISSUE THREAD

**Issue by djwillia** [nabla-containers/nabla-base-build#14]
`make -C go-base` fails for me and it appears to overwrite my local go installation, in this example in `/home/djwillia/go/bin`, which should probably have been changed to `/home/djwillia/nabla-base-build/gorump/go1.5/bin` as part of the build:

```
Installed Go for rumprun/amd64 in /home/djwillia/nabla-base-build/gorump/go
Installed commands in /home/djwillia/go/bin
cp -r /home/djwillia/nabla-base-build/gorump/go1.5 gorump
cp /home/djwillia/nabla-base-build/gorump/go1.5/bin/go go
cp: cannot stat '/home/djwillia/nabla-base-build/gorump/go1.5/bin/go': No such file or directory
Makefile:41: recipe for target 'gorump' failed
make[1]: *** [gorump] Error 1
make[1]: Leaving directory '/home/djwillia/nabla-base-build/go-base'
```
This seems to most likely have to do with the `env` variables I have:
```
$ env | grep GO
GOBIN=/home/djwillia/go/bin
GOPATH=/home/djwillia/go
```

**Comment by lumjjb** [comment]
Hi @djwillia, do test this whenever you can to see if it's still an issue - and we will close this issue!

**Comment by djwillia** [comment]
looks ok to me now!  Thanks!
