### ISSUE TITLE
Fix /dev hack for python nabla base image

### ISSUE THREAD

**Issue by lumjjb** [nabla-containers/nabla-base-build#5]
Python nabla base uses some references in /dev that is overwritten by mounting over the rootfs. This should be fixed in the proper way by the runtime in the future to respect system devices/runtime spec. 

The hack currently done is in the image, but this should be removed in the future:
https://github.com/nabla-containers/nabla-base-build/pull/4

**Comment by djwillia** [comment]
fyi this hack is used in the nginx and node bases as well, not just the python one.

**Comment by ricarkol** [comment]
Fixed with #6
